name: Get (possibly cached) Project/Pre-commit virtualenvs

runs:
  using: "composite"
  steps:
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5

    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install -qqq poetry

    - name: Load cached Poetry virtualenv, if available
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}-${{ hashFiles('.github/actions/poetry_cached/action.yml') }}-${{ steps.setup-python.outputs.python-version }}

    - name: Load cached pre-commit virtualenv
      id: cached-pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('.github/actions/poetry_cached/action.yml') }}-${{ steps.setup-python.outputs.python-version }}

    - name: Install poetry dependencies, only if cache wasn't found
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: |
        poetry install --no-interaction

    - name: Install pre-commit hooks, only if cache wasn't found
      if: steps.cached-pre-commit.outputs.cache-hit != 'true'
      shell: bash
      run: |
        poetry run pre-commit install-hooks
