name: Lints and Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, "*" ]
  workflow_dispatch:

jobs:
  lints_and_checks:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache_deps.yml

      - name: Static type checking with `mypy`
        run: |
          poetry run mypy

      - name: Linting with `pre-commit` and `ruff`
        run: |
          poetry run pre-commit run --all-files --show-diff-on-failure
