name: Lints and Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, "*" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install

      - name: Static type checking with `mypy`
        run: |
          poetry run mypy


      - name: Linting with `pre-commit` and `ruff`
        run: |
          poetry run pre-commit run --all-files --show-diff-on-failure
