name: Lints and Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, "*" ]
  workflow_dispatch:

jobs:
  lints_and_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get (possibly cached) uv/Pre-commit virtualenvs
        uses: ./.github/actions/uv_cached

      - name: Static type checking with `mypy`
        run: uv run mypy

      - name: Linting with `pre-commit` and `ruff`
        run: uv run pre-commit run --all-files --show-diff-on-failure
