name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, "*" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
    steps:
      - name: Checkout and get (possibly cached) Poetry/Pre-commit virtualenvs
        uses: ./.github/actions/poetry_cached

      - name: Run Tests
        run: |
          poetry run pytest
